config/routes.rb
Rails.application.routes.draw do
  get 'profiles/:id' => 'profiles#show', as: :profile

  get 'profiles' => 'profiles#index'

  resources :tweets do
    resource :like
  end
  resources :relationships
  devise_for :users

  root 'tweets#index'

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :likes

  validates :message, presence: true, length: { maximum: 140, too_long: "A tweet is only 140 characters max. Everybody knows that." }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships

  # Follower can see they are following someone. Followed can see they have a follower.
  has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_relationships, :source => :user
  has_many :likes

  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

 protected

 def configure_permitted_parameters

   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
     :name, :username, :bio, :location) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
     :current_password, :name, :username, :bio, :location) }

 end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_tweet

	def show
	end

	def create
		@tweet.likes.where(user_id: current_user.id).first_or_create

		respond_to do |format|
			format.html { redirect_to request.referrer }
		end
	end

	def destroy
		@tweet.likes.where(user_id: current_user.id).destroy_all

		respond_to do |format|
			format.html { redirect_to request.referrer }
		end
	end

	private

	def set_tweet
		@tweet = Tweet.find(params[:tweet_id])
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
		@relationship = current_user.relationships.build(:friend_id => params[:friend_id])
		if @relationship.save
			flash[:notice] = "Followed successfully."
			redirect_to profile_path(current_user.id)
		else
			flash[:notice] = "Unable to follow."
			redirect_to root_path
		end
	end

	def destroy
		# Current user looks through relationships to find the friend id
		@relationship = current_user.relationships.find(params[:id])
		@relationship.destroy
		flash[:notice] = "No longer following this user."
		redirect_to profile_path(current_user.id)
	end

	private

	def relationship_params
		# Params require in relationship to permit only user id and friend id
		params.require(:relationship).permit(:user_id, :friend_id)
	end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  def index
    @tweets = Tweet.all
  end

  def show
  end

  def edit
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Post was successfully updated.' }
      else 
        format.html { render :edit }
      end
    end
  end


  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was succesfully destroyed.' }
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <title>K80Twitter</title>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"></span> K80Twitter</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><a href="/tweets"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</li><li><a href="/profiles"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Users</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        <% end %></li>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
<%= yield %>
</div>
	

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/profiles/index.html.erb
<h1>All Users</h1>
<br>
<br>
<% @users.each do |user| %>
	<%= link_to user.username, profile_path(user) %> | 
	<%= link_to 'Edit', edit_user_registration_path %>
	<br>
<% end %>

app/views/profiles/show.html.erb
<div class="jumbotron" id="rotator"></div>
<div class="row">
	<div class="col-xs-4">
	<div class="panel panel-default">
		<%= image_tag @user.avatar %>
		<h3><%= @user.name %></h3>
		<h5 id="handle"><%= @user.username %></h5>
		<p><%= @user.bio %></p>

		<p><span class="glyphicon glyphicon-globe" aria-hidden="true"></span> <%= @user.location %></p>
		<p><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> Joined <%= @user.created_at.strftime("%B %Y") %></p>
		<br>
		<h5><span class="glyphicon glyphicon-triangle-right"aria-hidden="true"></span><span class="glyphicon glyphicon-triangle-right"aria-hidden="true"></span>  Following <%= @user.relationships.count %></h5>
		<% @user.relationships.each do |relationship| %>
			<%= link_to relationship.friend.name, profile_path(relationship.friend) %> <br>
		<% end %>
		<br>
		<h5> <span class="glyphicon glyphicon-triangle-left"aria-hidden="true"></span><span class="glyphicon glyphicon-triangle-left"aria-hidden="true"></span><%= pluralize(@user.inverse_relationships.count, "Follower") %></h5>
		<% @user.inverse_friends.each do |friend| %>
			<%= link_to friend.name, profile_path(friend) %> <br>
		<% end %>
	</div>
	</div>

<div class="col-xs-8">
	<div class="panel panel-default">
		<% @user.tweets.each do |tweet| %>
		<div class="panel-body">
			<strong><%= tweet.user.username %></strong><small> tweeted <%= time_ago_in_words(tweet.created_at) %></small>
			<br>
			<br>
			<%= tweet.message %>
		</div>
		<% end %>
	</div>
</div>

</div>

<% if current_user.id != @user.id %>
	<% if current_user.friends.include?(@user) %>
	<%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), method: :delete, class: "btn btn-danger" %>
	<% else %>
	<%= link_to "Follow", relationships_path(:friend_id => @user), method: :post, class: "btn btn-primary" %>
	<% end %>
<% end %>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
	<p><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-remove"), tweet_like_path(@tweet), method: :delete, class: "btn btn-info", type: "button", :title => "Unlike" %> Unlike</p>
<% else %>
	<p><%= link_to content_tag(:span, "", class: "glyphicon glyphicon-ok"), tweet_like_path(@tweet), method: :post, class: "btn btn-info", type: "button", :title => "Like" %> Like</p>
<% end %>

<p><button type="button" class="btn btn-info">
  <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
</button>
<%= @tweet.likes.count %> Likes</p>
<p><button type="button" class="btn btn-info">
  <span class="glyphicon glyphicon-user" aria-hidden="true"></span></button> Liked by:
<% @tweet.likes.each do |like| %>
<%= like.user.username %>
<br>
<% end %>
</p>
</div>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<% if @tweet.errors.any? %>
	<div class="error_explanation">
		<h2><%= pluralize(@tweet.errors.count, "Error") %> prohibited this tweet from being saved:</h2>
		<ul>
			<% @tweet.errors.full_messages.each do |message| %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="field">
	<%= f.label :message %><br>
	<%= f.text_field :message %>
</div>

<div class="field hidden">
	<%= f.label :user_id %>
	<%= f.text_field :user_id, value: current_user.id %>
</div>

<div class="actions">
	<%= f.submit "Tweet!", class: "btn btn-primary" %>
</div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet, class: "btn btn-primary" %> | 
<%= link_to 'Back', tweets_path, class: "btn btn-primary" %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>


<div class="span7 container">
<h3>Twitter Feed</h3>
	
	<% @tweets.each do |tweet| %>
<div class="col-md-11">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong><%= tweet.user.name %></strong>
				<%= tweet.user.username %><small> tweeted <%=time_ago_in_words(tweet.created_at) %> ago</small></div>
				<div class="panel-body">
					<%= tweet.message %><br><br>
				<small>
				<%= link_to content_tag(:span, "", class: "glyphicon glyphicon-eye-open"), tweet, class: "btn btn-info", type: "button" %>
				<%= link_to content_tag(:span, "", class: "glyphicon glyphicon-edit"), edit_tweet_path(tweet), class: "btn btn-info", type: "button" %>
				<%= link_to content_tag(:span, "", class: "glyphicon glyphicon-erase"), tweet, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-info", type: "button" %>
				<%= link_to content_tag(:span, "", class: "glyphicon glyphicon-option-horizontal"), tweet, class: "btn btn-info", type: "button" %>
				</small>
				</div>
		</div>
</div>
	<% end %>
<%= link_to 'New Tweet', new_tweet_path, class: "btn btn-default" %>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path, class: "btn btn-primary" %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<div class="col-md-11">
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="left">
				<h3><%= @tweet.user.name %></h3>
				<h5><%= @tweet.user.username %></h5>
				</div>
			<div class="right">
				<%= link_to content_tag(:span, "", class: "glyphicon glyphicon-edit"), edit_tweet_path(@tweet), class: "btn btn-info", type: "button" %>
				<%= link_to content_tag(:span, "", class: "glyphicon glyphicon-share-alt"), tweets_url, class: "btn btn-info", type: "button" %>
			</div>
			<div class="clear-both">
				<h2 id="tweet"><%= @tweet.message %></h2>
				<br><br>
				<%= render 'shared/likes' %>
			</div>

		</div>
	</div>


</div>
</div>